[package]
rust-version.workspace = true
name = "sdkwork-payment-repository-sqlx"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true


[lints]
workspace = true
[lib]
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
sdkwork_contract_service.workspace = true
sdkwork_payment_providers.workspace = true
sdkwork_payment_service.workspace = true
sdkwork-utils-rust.workspace = true
sqlx = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
