[package]
name = "sdkwork-api-payment-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-payment application HTTP plane."

[lib]
name = "sdkwork_api_payment_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork_payment_service_host.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork-web-core.workspace = true
sdkwork_routes_payment_app_api.workspace = true
sdkwork_routes_payment_backend_api.workspace = true
