environment = "production"

[http]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["payment.sdkwork.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "sdkwork.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["payment.birdcoder.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "birdcoder.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["payment.dtupay.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "dtupay.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["payment.sdkwork.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "sdkwork.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["payment.birdcoder.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "birdcoder.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["payment.dtupay.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "dtupay.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["payment.skubc.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "skubc.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["payment.skubc.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "skubc.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["payment.zowalk.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "zowalk.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["payment.zowalk.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "zowalk.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["payment.offer86.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "offer86.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["payment.offer86.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "offer86.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["payment.86offer.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "86offer.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["payment.86offer.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "86offer.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

